### ISSUE TITLE
MAJA 3.1.1 COTS?

### ISSUE THREAD

**Issue by RubenValDin** [olivierhagolle/Start_maja#26]
Hello,
I am trying to install MAJA-3.1.1 in Ubuntu 16.10. 
I have got MAJA COTS version 1.0.0 which was built on a RedHat Enterprise Linux OS version. Is there a new version of MAJA COTS built in Ubuntu? If so, how can I get it?
Thanks
Ruben

**Comment by petket-5** [comment]
Hi,

You will not need any more COTS package in order to install Maja. There are still some external components used inside of it, yet they have been already precompiled in the package that we're providing now with the version >3.x.

So in order to install it, you just have to execute the .run file. Don't forget to make it executable before (chmod +x).

Kind regards,
Peter
